// templates/svelte/src/lib/components/NetworkPill.svelte
<script lang="ts">
	import { networkStatus } from "@stellar-scaffold/app-lib"
	import { address, networkPassphrase } from "../stores/wallet"

	const status = $derived(networkStatus($address, $networkPassphrase))
</script>

<div
	class="network-pill"
	class:network-pill--mismatch={status.state === "mismatch"}
	class:network-pill--unverified={status.state === "unverified"}
	title={status.title}
>
	<span class="network-dot network-dot--{status.state}"></span>
	{status.appNetwork}
</div>

// templates/react/src/components/NetworkPill.tsx
import { networkStatus } from "@stellar-scaffold/app-lib"
import React from "react"
import { useWallet } from "../hooks/useWallet"

const NetworkPill: React.FC = () => {
	const { networkPassphrase, address } = useWallet()
	const { appNetwork, state, title } = networkStatus(address, networkPassphrase)

	return (
		<div
			className={`network-pill${state === "mismatch" || state === "unverified" ? ` network-pill--${state}` : ""}`}
			title={title}
		>
			<span className={`network-dot network-dot--${state}`} />
			{appNetwork}
		</div>
	)
}

export default NetworkPill
