// templates/react/src/components/ConnectAccount.tsx
import { stellarNetwork } from "@stellar-scaffold/app-lib"
import React from "react"
import FundAccountButton from "./FundAccountButton"
import NetworkPill from "./NetworkPill"
import { WalletButton } from "./WalletButton"

const ConnectAccount: React.FC = () => {
	return (
		<div className="connect-account">
			<NetworkPill />
			{stellarNetwork !== "PUBLIC" && <FundAccountButton />}
			<WalletButton />
		</div>
	)
}

export default ConnectAccount

// templates/svelte/src/lib/components/ConnectAccount.svelte
<script lang="ts">
	import { stellarNetwork } from "@stellar-scaffold/app-lib"
	import FundAccountButton from "./FundAccountButton.svelte"
	import NetworkPill from "./NetworkPill.svelte"
	import WalletButton from "./WalletButton.svelte"
</script>

<div class="connect-account">
	<NetworkPill />
	{#if stellarNetwork !== "PUBLIC"}
		<FundAccountButton />
	{/if}
	<WalletButton />
</div>
