// templates/react/src/components/WalletButton.tsx
import {
	connectWallet,
	profileModal,
	shortAddress,
} from "@stellar-scaffold/app-lib"
import { useWallet } from "../hooks/useWallet"

export const WalletButton = () => {
	const { address, isPending, balances } = useWallet()

	if (!address) {
		return (
			<button onClick={() => void connectWallet()} disabled={isPending}>
				{isPending ? "Loading..." : "Connect"}
			</button>
		)
	}

	return (
		<div className="wallet-connected" style={{ opacity: isPending ? 0.6 : 1 }}>
			<span className="wallet-balance">
				{balances?.xlm?.balance ?? "-"} XLM
			</span>

			<button className="wallet-profile" onClick={() => void profileModal()}>
				{shortAddress(address)}
			</button>
		</div>
	)
}

// templates/svelte/src/lib/components/WalletButton.svelte
<script lang="ts">
	import {
		connectWallet,
		profileModal,
		shortAddress,
	} from "@stellar-scaffold/app-lib"
	import { address, balances, isPending } from "../stores/wallet"
</script>

{#if !$address}
	<button onclick={() => void connectWallet()} disabled={$isPending}>
		{$isPending ? "Loading..." : "Connect"}
	</button>
{:else}
	<div class="wallet-connected" style:opacity={$isPending ? 0.6 : 1}>
		<span class="wallet-balance">{$balances?.xlm?.balance ?? "-"} XLM</span>

		<button class="wallet-profile" onclick={() => void profileModal()}>
			{shortAddress($address)}
		</button>
	</div>
{/if}
